### ISSUE TITLE
Ошибка при запуске на HTC P3400

### ISSUE THREAD

**Issue by GMaks24** [Limows/LimFTPClient_WM#1]
HTC P3400 (Windows Mobile 5.0)
При запуске ошибка:
MissingMethodException Не найдено имя файла или сборки "System.Windows.Forms, Version=3.5.0.0, Culture=neutral, PublicKeyToken=969DB8053D3322AC" либо одна из зависимостей.

**Comment by Limows** [comment]
А NetCF 3.5 на устройстве установлен?

**Comment by GMaks24** [comment]
Да действительно, с первого раза не установилась. С NetCF 3.5 приложение запустилось. Благодарю :)
